version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.0
